# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t <cf-target> set-pipeline -p maven-cf-example -c pipeline.yml -l pipeline-secrets.yml
---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/diconium/concourse-maven-cf.git
    branch: master

- name: cloud-foundry
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/build.yml
  - put: cloud-foundry
    params:
      manifest: source-code/manifest.yml
      path: build-output/concourse-maven-cf-0.0.1-SNAPSHOT.jar
